server:
  port: ${PORT:8080}

spring:
  application:
    name: montola
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    jwt:
      secret: ${SECURITY_JWT_SECRET}
      expiration-minutes: ${SECURITY_JWT_EXPIRATION_MINUTES:60}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_APP_EMAIL}
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  frontend-url: ${FRONTEND_URL:http://localhost:3000}
